### ISSUE TITLE
Print the address of the selected window 

### ISSUE THREAD

**Issue by 3333juul** [zakk4223/hyprland-easymotion#10]
Is there a way to get the address info after selecting the window? I need it for scripting purpose.

**Comment by zakk4223** [comment]
The action just uses hyprland's 'exec' functionality, so you could just exec a shell script and then do whatever action+scripting stuff you needed in it.

It might not be too difficult to emit IPC events tho, would that be helpful?

**Comment by zakk4223** [comment]
What version of hyprland are you using? If you're still on 0.40 it probably isn't using the latest commit due to pins.

**Comment by zakk4223** [comment]
Done!
