### ISSUE TITLE
Non-hacky option for non-border

### ISSUE THREAD

**Issue by modestbadger1773** [zakk4223/hyprland-easymotion#2]
Currently possible by submitting an invalid hex colour code. (eg: fffffff) or setting width to 0. But it would be nice to have it as an option that doesn't risk anything weird going on.

Otherwise really great tool. Exactly what I was looking for.

**Comment by zakk4223** [comment]
It follows the same convention as Hyprland, where bordersize=0 means no border. That fully disables border rendering. I should probably note it in the docs tho.
