### ISSUE TITLE
Add the ability to define submap keybindings that work when being in easymotion mode

### ISSUE THREAD

**Issue by 3333juul** [zakk4223/hyprland-easymotion#4]
It would be nice to have something like this in plugin's config:
```
submap=alt,tab, exec, hyprctl dispatch easymotionexit
```
this would add more flexibility to the plugin and would make it possible to execute and close easymotion with a single keybinding

**Comment by zakk4223** [comment]
You can! I should probably document the submap name in the readme tho...

submap=__easymotionsubmap__
bind,alt,tab,exec hyprctl dispatch easymotionexit
submap=reset


(escape will still work to exit, but your bind will also work)
